apiVersion: v2
name: cert-manager
description: Wrapper chart for cert-manager, including our Let's Encrypt (Cloudflare DNS01) ClusterIssuer
type: application
version: 0.1.0
appVersion: "1.16.2"
dependencies:
  - name: cert-manager
    version: "*"
    repository: https://charts.jetstack.io
