# copy seccomp profiles to all nodes
- name: Copy seccomp Profiles to All Nodes
  hosts: kubernetes
  gather_facts: no
  become: yes

  tasks:
    - name: Copy each file over that matches the given pattern
      copy:
        src: "{{ item }}"
        dest: "/var/lib/kubelet/seccomp/profiles/"
        owner: "root"
        mode: 0600
      with_fileglob:
        - "./seccomp-profiles/*.json"
