- name: Initialize Kubernetes master
  hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.32.0.0/12
      register: kubeadm_output

    - name: Save kubeadm join command
      shell: echo "{{ kubeadm_output.stdout_lines | select('search', 'kubeadm join') | list | first }}" > /tmp/kubeadm_join_command.sh

    - name: Configure kubectl for pi user
      shell: |
        mkdir -p /home/pi/.kube
        cp -i /etc/kubernetes/admin.conf /home/pi/.kube/config
        chown pi:pi /home/pi/.kube/config
