- name: Install Kubernetes prerequisites and containerd
  hosts: kubernetes
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install common dependencies
      apt:
        name: "{{ common_packages }}"
        state: present

    - name: Add kubernetes repo
      shell: | 
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gpg
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update

    - name: install kubernetes components
      shell:
        sudo apt install -y kubelet kubeadm kubectl

    - name: Add containerd repository and install
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
      register: repo_added

    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee "{{ containerd_config_file }}"

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: hold package versions
      shell: |
        sudo apt-mark hold kubelet kubeadm kubectl containerd.io
