[masters]
master1 ansible_host=192.168.86.104

[workers]
# worker1 ansible_host=192.168.1.11 ansible_user=ubuntu
# worker2 ansible_host=192.168.1.12 ansible_user=ubuntu

[kubernetes:children]
masters
# workers
