- name: Deploy argocd
  hosts: masters
  gather_facts: no
  become: yes

  tasks:
    - name: Add the ArgoCD Helm repository
      command: helm repo add argo https://argoproj.github.io/argo-helm
      changed_when: false

    - name: Update Helm repositories
      command: helm repo update
      changed_when: false

    - name: Create argocd namespace
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy ArgoCD using Helm
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        state: present

    - name: Wait for ArgoCD server pod to be ready
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      command: kubectl wait --namespace argocd --for=condition=ready pod -l app.kubernetes.io/name=argocd-server --timeout=300s
      changed_when: false

    - name: Get the initial admin password
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      command: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password
      changed_when: false

    - name: Display ArgoCD admin password
      debug:
        msg: "ArgoCD Admin Password: {{ argocd_password.stdout }}"

